pipeline {
    agent any
    tools { 
        maven 'maven3.5' 
        jdk 'java1.8-201' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

        stage ('scm') {
            steps {
                 git credentialsId: '78c165e4-a738-46c7-b468-984310b0a9c6', url: 'https://github.com/Priyasrivinod/project1.git'
            }
        }
        
        stage ('build') {
	   
            steps {
                sh 'mvn clean install'
            }
		}
    }
}
